//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Marca
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Marca()
        {
            this.MarcaObraSocial = new HashSet<MarcaObraSocial>();
        }
    
        public int Id { get; set; }
        public string Descripcion { get; set; }
        public string LaboratorioId { get; set; }
        public string Precio { get; set; }
        public string MedicamentoId { get; set; }
    
        public virtual Laboratorio Laboratorio { get; set; }
        public virtual Medicamento Medicamento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MarcaObraSocial> MarcaObraSocial { get; set; }
    }
}
