//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MarcaObraSocial
    {
        public int Id { get; set; }
        public string Detalle { get; set; }
        public string IdMarca { get; set; }
        public string IdObraSocial { get; set; }
    
        public virtual ObraSocial ObraSocial { get; set; }
        public virtual Marca Marca { get; set; }
    }
}
